### ISSUE TITLE
Error in decoding cB.1.617.1.json

### ISSUE THREAD

**Issue by yp** [cov-lineages/constellations#5]
When running `scorpio` I get the following error. I found that the related JSON file has been already fixed in commit ac56ab50d825024d4bcd68c29bf2403eb5a3c990. Would you mind to put out a new release so that pangolin can update the definitions?

Thanks for your work

```
Traceback (most recent call last):
  File "/opt/conda/envs/pangolin/bin/scorpio", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/scorpio/__main__.py", line 220, in main
    args.func(args)
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/scorpio/subcommands/classify.py", line 7, in run
    classify_constellations(options.input,
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/scorpio/scripts/type_constellations.py", line 567, in classify_constellations
    constellation, variants, rules = parse_variants_in(reference_seq, features_dict, constellation_file,
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/scorpio/scripts/type_constellations.py", line 349, in parse_variants_in
    variant_list, name, rule_dict = parse_json_in(refseq, features_dict, variants_file, constellation_names, include_ancestral=include_ancestral)
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/scorpio/scripts/type_constellations.py", line 225, in parse_json_in
    json_dict = json.load(in_json, strict=False)
  File "/opt/conda/envs/pangolin/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/conda/envs/pangolin/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/opt/conda/envs/pangolin/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/envs/pangolin/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 19 column 5 (char 542)
```

**Comment by mcroxen** [comment]
yp - this should have been corrected a few days ago (see: https://github.com/cov-lineages/constellations/issues/4)

I would recommend updating

**Comment by yp** [comment]
Yes, now I was able to update. Apparently, the constellation data did not update within pangolin without a new release.

Thanks
